[[language]]
name = "rust"
language-servers = ["rust-analyzer"]
formatter = {command = "rustfmt"}
auto-format = true
indent = { tab-width = 4, unit = "t" }

[language-server.rust-analyzer]
command = "rust-analyzer"

[[language]]
name = "html"
auto-format = true
formatter = { command = "prettier", args = ["--stdin-filepath", "%{buffer_name}"] }
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]

[[language]]
name = "css"
auto-format = true
formatter = { command = "prettier", args = ["--stdin-filepath", "%{buffer_name}"]}
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]
 
[[language]]
name = "javascript"
auto-format = true
formatter = { command = "prettier", args = ["--stdin-filepath", "%{buffer_name}"] }
language-servers = ["typescript-language-server"]

[[language]]
name = "jsx"
auto-format = true
formatter = { command = "prettier", args = ["--stdin-filepath", "%{buffer_name}"] }
language-servers = [ "typescript-language-server", "tailwindcss-ls"]

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "prettier", args = ["--stdin-filepath", "%{buffer_name}"] }
language-servers = [ "typescript-language-server", "tailwindcss.ks" ]

[[language]]
name = "json"
auto-format = true
formatter = { command = "prettier", args = ["--stdin-filepath", "%{buffer_name}"] }
language-servers = ["vscode-json-language-server"]
