set -g default-terminal "tmux-256color"

set -g mouse 		on
set -g history-limit 	10000
set -g escape-time 	10
set -g focus-events	on

# Windows and panels start with 1
set -g base-index	1
set -g pane-base-index	1

# Reorder windows after close one
set -g renumber-windows	on

# Copy mode (like in Vim)
set -g mode-keys 	vi


# Windows and panels ___________________________
# Create a widow in current direcgtory
bind-key c new-window -c "#{pane_current_path}"

# Devide conserving current directory
unbind-key %
unbind-key '"'

bind-key . split-window -h -c "#{pane_current_path}"
bind-key - split-window -v -c "#{pane_current_path}"


# Navegation
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R


# Redimention of pannels
bind-key -r H resize-pane -L 5
bind-key -r J resize-pane -D 5
bind-key -r K resize-pane -U 5
bind-key -r L resize-pane -R 5


# Copy mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi s send-keys -X copy-selecion-and-cancel 


# Lazygit
bind-key g new-window \
	-n "lazygit" \
	-c "#{pane_current_path}" \
	"lazygit"


# Reload config
bind-key r source-file ~/.config/tmux/tmux.conf \; \
	display-message "[INFO] Tmux configuration is reloaded"


# State bar
set -g status-position 			bottom
set -g status-interval 			5

set -g status-left 			" #S "
set -g status-right			" %Y-%m-%d %H:%M "

setw -g window-status-format		" #I:#W "
setw -g window-status-current-format	" [#I:#W] "


