# (UI.dev Inspired) Colors for Wezterm

[colors]
background = '#0d1117'  # Fondo oscuro similar al fondo de la página
foreground = '#c9d1d9'  # Texto gris claro para buen contraste

cursor_bg = '#58a6ff'  # Azul vibrante como los acentos de la página
cursor_border = '#58a6ff'
cursor_fg = '#0d1117'  # Negro para contrastar con el cursor

selection_bg = '#1f6feb'  # Fondo de selección en azul más intenso
selection_fg = '#c9d1d9'  # Texto seleccionado en gris claro

ansi = [
    '#21262d',  # Negro oscuro/gris para el terminal
    '#ff7b72',  # Rojo brillante
    '#3fb950',  # Verde vibrante
    '#d29922',  # Amarillo dorado
    '#58a6ff',  # Azul claro vibrante
    '#bc8cff',  # Púrpura brillante
    '#39c5cf',  # Cian
    '#b1bac4',  # Gris claro
]
brights = [
    '#2d333b',  # Gris más oscuro
    '#ffa198',  # Rojo más claro
    '#56d364',  # Verde más claro
    '#e3b341',  # Amarillo más claro
    '#79c0ff',  # Azul más claro
    '#d2a8ff',  # Púrpura más claro
    '#56d4dd',  # Cian más claro
    '#f0f6fc',  # Blanco casi puro
]

